 platform :ios, '9.0'

target 'BaseProject' do
  

  # Pods for BaseProject

pod 'AFNetworking', '~> 3.2.1'

pod 'JSONModel', '~> 1.7.0'

pod 'MJRefresh', '~> 3.1.15.3'

pod 'FMDB', '~> 2.7.2'

pod 'MBProgressHUD', '~> 1.1.0'

pod 'SDWebImage', '~> 4.4.1'


pod 'MBProgressHUD+Add', '~> 0.0.2'

end
